[package]
name = "animal_center"
version = "0.1.0"
authors = ["futugyousuzu <17871902+futugyu@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "3", features = ["rustls"] }
rustls = "0.18"
actix-cors = "0.5"
actix-multipart = "0.3"
actix-files = "0.5"
sanitize-filename = "0.3"
actix-service = "1"
async-graphql="2"
async-graphql-actix-web = "2"
dotenv = "0.15"
futures = "0.3"

opentelemetry = { version = "0.12", default-features = false, features = ["trace", "metrics","tokio-support"] }
opentelemetry-jaeger = { version = "0.11"  }
actix-web-opentelemetry = {version = "0.10",features = ["metrics"]  }
tracing = "0.1"
tracing-opentelemetry = "0.11"
tracing-subscriber = "0.2"
tracing-futures = { version = "0.2", default-features = false }
opentelemetry-prometheus ="0.5" 
tokio = { version = "0.2", default-features = false, features = ["rt-core", "blocking", "time", "stream"] }
 
serialize = {path= "../serialize" }
tool = {path= "../tool" }
entity = {path= "../entity" }
model = {path= "../model" }
infrastruct = {path= "../infrastruct" }
repository = {path= "../repository"}
service = {path= "../service"}
