[package]
name = "serialize"
version = "0.2.0"
authors = ["futugyousuzu <17871902+futugyu@users.noreply.github.com>"]
edition = "2021"

[dependencies]
serde = "1"
serde_json ="1"
chrono = "0.4"

tool = {path= "../tool" }