---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: adoption
  namespace: animal
  labels:
    app: animal
    service: adoption
spec:
  replicas: 1
  selector:
    matchLabels:
      service: adoption
  template:
    metadata:
      labels:
        app: animal
        service: adoption
    spec:
      initContainers:
        - name: init-adoption-database
          image: futugyousuzu/adoption-migration:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: ASPNETCORE_ENVIRONMENT
            valueFrom:
             configMapKeyRef:
              name: adoption-cm
              key: ASPNETCORE_ENVIRONMENT
          volumeMounts:
          - name: config-volume
            mountPath: /app/appsettings.json
            subPath: appsettings.json
            readOnly: true
      containers:
        - name: adoption-api
          image: futugyousuzu/adoption:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 81
              protocol: TCP
          env: # 定义环境变量
          - name: ASPNETCORE_ENVIRONMENT # 请注意这里和 ConfigMap 中的键名是不一样的
            valueFrom:
             configMapKeyRef:
              name: adoption-cm           # 这个值来自 ConfigMap
              key: ASPNETCORE_ENVIRONMENT # 需要取值的键
          volumeMounts:
          - name: config-volume
            mountPath: /app/appsettings.json
            subPath: appsettings.json # 有subPath不能热更新，需要重新放置appsetting.json，修改代码
            readOnly: true          
          resources:
           limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
        - name: config-volume
          configMap:
            name: adoption-cm
            # 来自 ConfigMap 的一组键，将被创建为文件
            items:
             - key: "appsettings"
               path: "appsettings.json"

---

kind: Service
apiVersion: v1
metadata:
  name: adoption-api
  namespace: animal
  labels:
    app: animal
    service: adoption
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
      protocol: TCP
      name: http
  selector:
    service: adoption