kind: ConfigMap
apiVersion: v1
metadata:
  name: animal-center-cm
  namespace: animal
  labels:
    app: animal
    service: animal-center
data:
  mongodb_uri: mongodb
  api_key: apikey
  api_value: apivalue
  amqp_addr: rabbitmq
  server_address: animal-center
  file_upload_path: fileupload

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: animal-center
  namespace: animal
  labels:
    app: animal
    service: animal-center
spec:
  replicas: 1
  selector:
    matchLabels:
      service: animal-center
  template:
    metadata:
      labels:
        app: animal
        service: animal-center
    spec:
      containers:
        - name: animal-center-api
          image: futugyousuzu/back_animal_center:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 81
              protocol: TCP
          envFrom:
            - configMapRef:
                name: animal-center-cm
          resources:
           limits:
            memory: "128Mi"
            cpu: "100m"

---
kind: Service
apiVersion: v1
metadata:
  name: animal-center-api
  namespace: animal
  labels:
    app: animal
    service: animal-center
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
      protocol: TCP
      name: http
  selector:
    service: animal-center
