[package]
name = "model"
version = "0.1.0"
authors = ["futugyousuzu <17871902+futugyu@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
validator = { version = "0.13", features = ["derive"] }
actix-web = "3"
bson = "1"
async-graphql="2"

serialize = {path= "../serialize" }
tool = {path= "../tool" }
entity = {path= "../entity" }