Database:
    Host: 192.168.15.136
    Port: 15432
    User: postgres
    Password: 123456
    Dbname: go
Client:
 - ID: 222222
   Secret: 22222222
   Domain: http://localhost:8082
   Scopes: 
    - read
    - write
 - ID: 333333
   Secret: 33333333
   Domain: http://localhost:8083
   Scopes: 
    - read