name: .NET

on:
  workflow_dispatch:
  push:
    paths:
    - Adoption/**
    - .github/workflows/adoption.yml
    
  pull_request:
    branches: [ master ]
    paths:
    - Adoption/**
    - .github/workflows/adoption.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}     
       
    - name: build migration image
      if: github.ref_name != 'master'
      uses: docker/build-push-action@v5
      with:
       push: false
       tags: futugyousuzu/adoption-migration:latest
       context: ./Adoption
       file: ./Adoption/Adoption.DbMigrator/Dockerfile     
       
    - name: build adoption image
      if: github.ref_name != 'master'
      uses: docker/build-push-action@v5
      with:
       push: false
       tags: futugyousuzu/adoption:latest
       context: ./Adoption
       file: ./Adoption/Adoption.Host/Dockerfile
       
    - name: Push migration to Docker Hub
      if: github.ref_name == 'master'
      uses: docker/build-push-action@v5
      with:
       push: true
       tags: futugyousuzu/adoption-migration:latest
       context: ./Adoption
       file: ./Adoption/Adoption.DbMigrator/Dockerfile     
       
    - name: Push to Docker Hub
      if: github.ref_name == 'master'
      uses: docker/build-push-action@v5
      with:
       push: true
       tags: futugyousuzu/adoption:latest
       context: ./Adoption
       file: ./Adoption/Adoption.Host/Dockerfile
