name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - AnimalCenter/**
    - .github/workflows/basket-api.yml
    
  pull_request:
    branches: [ master ]
    paths:
    - AnimalCenter/**
    - .github/workflows/basket-api.yml
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
       cd AnimalCenter
       cargo build --verbose
    - name: Run tests
      run: |      
       cd AnimalCenter
       cargo test --verbose
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: futugyousuzu/animal-center
        tag_with_ref: true
        context: AnimalCenter
