name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - AnimalCenter/**
    - .github/workflows/rust.yml
    
  pull_request:
    branches: [ master ]
    paths:
    - AnimalCenter/**
    - .github/workflows/rust.yml
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
       push: true
       tags: futugyousuzu/back_animal_center:latest
       context: AnimalCenter
