name: Shuttle Deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - AnimalCenter/**
    - .github/workflows/animal_center.yml
    
  pull_request:
    branches: [ master ]
    paths:
    - AnimalCenter/**
    - .github/workflows/animal_center.yml
    - .github/workflows/shuttle.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./AnimalCenter
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          working-directory: ${{env.working-directory}}
          allow-dirty: "true"
          secrets: |
            mongodb_uri = '${{ secrets.MONGODB_URI }}'
            table_name = '${{ secrets.TABLE_NAME }}'
            api_key = '${{ secrets.API_KEY }}'
            api_value = '${{ secrets.API_VALUE }}'
            server_address = '${{ secrets.SERVER_ADDRESS }}'
            amqp_addr = '${{ secrets.AMQP_ADDR }}'
            file_upload_path = '${{ secrets.FILE_UPLOAD_PATH }}'
            honeycomb_api_key = '${{ secrets.HONEYCOMB_API_KEY }}'
